target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'composeApp', :path => '../composeApp'
  pod 'GoogleMaps', '9.1.1' # latest version
  pod 'Google-Maps-iOS-Utils', '6.0.0' # latest version
end